export enum DatabaseModelEnum {
  USER_MODEL_NAME = 'user',
  OAUTH_TOKEN_MODEL_NAME = 'oauth_token',
  TASK_MODEL_NAME = 'task',
  TASK_STATUS_MODEL_NAME = 'task_status',
  ERROR_MODEL_NAME = 'error',
  COMMENT_MODEL_NAME = 'comment',
  CLIENT_MODEL_NAME = 'client',
  CLIENT_STATUS_MODEL_NAME = 'client_status',
  CLIENT_FILE_MODEL_NAME = 'client_file',
  CITY_MODEL_NAME = 'city',
  USER_CITY_MODEL_NAME = 'user_city',
  APPLICATION_MODEL_NAME = 'application',
  GROUP_MODEL_NAME = 'group',
  CLIENT_GROUP_MODEL_NAME = 'client_group',
  COURSE_MODEL_NAME = 'course',
  APPLICATION_FILE_MODEL_NAME = 'application_file',
  PAYMENT_MODEL_NAME = 'payment',
  PAYMENT_STATUS_MODEL_NAME = 'payment_status',
  PAYMENT_TYPE_MODEL_NAME = 'payment_type',
  DISCOUNT_MODEL_NAME = 'discount',
  APPLICATION_DISCOUNT_MODEL_NAME = 'application_discount',
  SOURCE_MODEL_NAME = 'source',
  APPLICATION_SOURCE_MODEL_NAME = 'application_source',
  PAYMENT_FILE_MODEL_NAME = 'payment_file'
}
